# 运行配置
run:
  go: 1.18
  # 要使用的CPU核心数
  concurrency: 4

  # 分析超时，例如 30s, 5m，默认是 1m
  timeout: 10m

  # 包管理模式，go modules使用readonly
  # 可用的值范围 readonly|release|vendor
  modules-download-mode:  readonly

  # 当有多少个问题存在时则退出检查，默认是1
  issues-exit-code: 500

  # 是否包含测试文件
  tests: false

  # 要跳过检查的目录
  skip-dirs:
    - load-test
    - tcp-client
    - to-bin
    - script
    - visual-battle-client

  # 允许跳过目录
  skip-dirs-use-default: true

  # 跳过文件
  skip-files:

# 输出配置
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: json

  # 打印行号
  print-issued-lines: true

  # 打印检查器的名称
  print-linter-name: true

# 质量检查配置
linters-settings:
  # 错误检查
  errcheck:
    # 检查类型错误
    check-type-assertions: false

    # 检查空标识符
    check-blank: true

    # 忽略文件
  #    ignore: fmt:.*,io/ioutil:^Read.*

  funlen:
    lines: 60
    statements: 40

  govet:
    # 检查影子变量
    check-shadowing: true
    # 根氟名称启用或禁用分析器
    disable-all: true
    enable-all: false
    enable:
      - unusedwrite

  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8

  # 检查函数的复杂程度
  gocyclo:
    # 最小复杂性
    min-complexity: 35

  gocognit:
    # 最小复杂性
    min-complexity: 35

  maligned:
    # 为内存对齐优化给出新的结构体字段排序建议
    suggest-new: true
    # 自动修复
    auto-fix: true

  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100

  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 3
  cyclop:
    max-complexity: 30 #函数复杂度


  depguard:
    list-type: blacklist
    include-go-root: false

  lll:
    line-length: 240
    tab-width: 1

  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - someword

  nakedret:
    # 如果func的代码行数比这个设置的多，并且它的返回值是空的，就会产生问题，默认是30
    max-func-lines: 30

  unused:
    check-exported: true

  stylecheck:
    checks:
      - ST1000    #Incorrect or missing package comment
      #      - ST1001    #Dot imports are discouraged
      #      - ST1003    #Poorly chosen identifier
      #      - ST1005    #Incorrectly formatted error string
      - ST1006    #Poorly chosen receiver name
      #      - ST1008    #A function’s error value should be its last return value
      - ST1011    #Poorly chosen name for variable of type time.Duration
      #      - ST1012    #Poorly chosen name for error variable
      - ST1013    #Should use constants for HTTP error codes, not magic numbers
      - ST1015    #A switch’s default case should be the first or last case
      #      - ST1016    #Use consistent method receiver names
      - ST1017    #Don’t use Yoda conditions
      - ST1018    #Avoid zero-width and control characters in string literals
      - ST1019    #Importing the same package multiple times
      - ST1020    #The documentation of an exported function should start with the function’s name
  #      - ST1021    #The documentation of an exported type should start with type’s name
  #      - ST1022    #The documentation of an exported variable or constant should start with variable’s name
  #      - ST1023    #Redundant type in variable declaration

  staticcheck:
    checks:
      - all
  #      - SA1000	#	Invalid regular expression
  #      - SA1001	#	Invalid template
  #      - SA1002	#	Invalid format in time.Parse
  #      - SA1003	#	Unsupported argument to functions in encoding/binary
  #      - SA1004	#	Suspiciously small untyped constant in time.Sleep
  #      - SA1005	#	Invalid first argument to exec.Command
  #      - SA1006	#	Printf with dynamic first argument and no further arguments
  #      - SA1007	#	Invalid URL in net/url.Parse
  #      - SA1008	#	Non-canonical key in http.Header map
  #      - SA1010	#	(*regexp.Regexp).FindAll called with n == 0, which will always return zero results
  #      - SA1011	#	Various methods in the strings package expect valid UTF-8, but invalid input is provided
  #      - SA1012	#	A nil context.Context is being passed to a function, consider using context.TODO instead
  #      - SA1013	#	io.Seeker.Seek is being called with the whence constant as the first argument, but it should be the second
  #      - SA1014	#	Non-pointer value passed to Unmarshal or Decode
  #      - SA1015	#	Using time.Tick in a way that will leak. Consider using time.NewTicker, and only use time.Tick in tests, commands and endless functions
  #      - SA1016	#	Trapping a signal that cannot be trapped
  #      - SA1017	#	Channels used with os/signal.Notify should be buffered
  #      - SA1018	#	strings.Replace called with n == 0, which does nothing
  #      - SA1019	#	Using a deprecated function, variable, constant or field
  #      - SA1020	#	Using an invalid host:port pair with a net.Listen-related function
  #      - SA1021	#	Using bytes.Equal to compare two net.IP
  #      - SA1023	#	Modifying the buffer in an io.Writer implementation
  #      - SA1024	#	A string cutset contains duplicate characters
  #      - SA1025	#	It is not possible to use (*time.Timer).Reset’s return value correctly
  #      - SA1026	#	Cannot marshal channels or functions
  #      - SA1027	#	Atomic access to 64-bit variable must be 64-bit aligned
  #      - SA1028	#	sort.Slice can only be used on slices
  #      - SA1029	#	Inappropriate key in call to context.WithValue
  #      - SA1030	#   Invalid argument in call to a strconv function

  unparam:
    check-exported: false
  gocritic:
    enabled-checks:
      - appendAssign
      - appendCombine
      - argOrder
      - assignOp
      - badCall
      - badCond
      - badLock
      - badRegexp
      - boolExprSimplify
      - builtinShadow
      - builtinShadowDecl
      - captLocal
      - caseOrder
      - codegenComment
      - commentFormatting
      - commentedOutCode
      - commentedOutImport
      - defaultCaseOrder
      - deferUnlambda
      # - deferInLoop
      - deprecatedComment
      - docStub
      - dupArg
      - dupBranchBody
      - dupCase
      - dupImport
      - dupSubExpr
      - elseif
      # - emptyDecl
      - emptyFallthrough
      - emptyStringTest
      - equalFold
      - evalOrder
      - exitAfterDefer
      - exposedSyncMutex
      - externalErrorReassign
      - filepathJoin
      - flagDeref
      - flagName
      - hexLiteral
      - httpNoBody
      - hugeParam
      - ifElseChain
      - importShadow
      - indexAlloc
      - initClause
      - ioutilDeprecated
      - mapKey
      - methodExprCall
      - nestingReduce
      - newDeref
      - nilValReturn
      - octalLiteral
      - offBy1
      - paramTypeCombine
      - preferDecodeRune
      - preferFilepathJoin
      - preferFprint
      - preferStringWriter
      - preferWriteByte
      - ptrToRefParam
      - rangeExprCopy
      - rangeValCopy
      - redundantSprint
      - regexpMust
      - regexpPattern
      - regexpSimplify
      - returnAfterHttpError
      - ruleguard
      - singleCaseSwitch
      - sliceClear
      - sloppyLen
      - sloppyReassign
      - sloppyTypeAssert
      - sortSlice
      - sprintfQuotedString
      - sqlQuery
      - stringConcatSimplify
      - stringXbytes
      - switchTrue
      - syncMapLoadAndDelete
      - timeExprSimplify
      - tooManyResultsChecker
      - truncateCmp
      - typeAssertChain
      - typeDefFirst
      - typeSwitchVar
      - typeUnparen
      - underef
      - unlabelStmt
      - unlambda
      - unnamedResult
      - unnecessaryBlock
      - unnecessaryDefer
      - unslice
      - valSwap
      - weakCond
      - whyNoLint
      - wrapperFunc
  disabled-checks:
    enabled-tags:
      - performance
    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32

linters:
  disable-all: true
  enable-all: false
  enable:
    - stylecheck
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - makezero
    - maligned # 内存对齐

  fast: true
#  presets:
#    - error
#    - import
