// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type RoleReachItem struct {
	Id         values.Integer `mapstructure:"id" json:"id"`
	ReduceTime values.Integer `mapstructure:"reduce_time" json:"reduce_time"`
}

// parse func
func ParseRoleReachItem(data *Data) {
	if err := data.UnmarshalKey("role_reach_item", &h.roleReachItem); err != nil {
		panic(errors.New("parse table RoleReachItem err:\n" + err.Error()))
	}
	for i, el := range h.roleReachItem {
		h.roleReachItemMap[el.Id] = i
	}
}

func (i *RoleReachItem) Len() int {
	return len(h.roleReachItem)
}

func (i *RoleReachItem) List() []RoleReachItem {
	return h.roleReachItem
}

func (i *RoleReachItem) GetRoleReachItemById(id values.Integer) (*RoleReachItem, bool) {
	index, ok := h.roleReachItemMap[id]
	if !ok {
		return nil, false
	}
	return &h.roleReachItem[index], true
}
