// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type AnecdotesGame5Option struct {
	AnecdotesGame5Id values.Integer                    `mapstructure:"anecdotes_game5_id" json:"anecdotes_game5_id"`
	Id               values.Integer                    `mapstructure:"id" json:"id"`
	PowerType        values.Integer                    `mapstructure:"power_type" json:"power_type"`
	Time             values.Integer                    `mapstructure:"time" json:"time"`
	Reward           map[values.Integer]values.Integer `mapstructure:"reward" json:"reward"`
	DropListId       values.Integer                    `mapstructure:"drop_list_id" json:"drop_list_id"`
	Icon             []string                          `mapstructure:"icon" json:"icon"`
}

// parse func
func ParseAnecdotesGame5Option(data *Data) {
	if err := data.UnmarshalKey("anecdotes_game5_option", &h.anecdotesGame5Option); err != nil {
		panic(errors.New("parse table AnecdotesGame5Option err:\n" + err.Error()))
	}
	for i, el := range h.anecdotesGame5Option {
		if _, ok := h.anecdotesGame5OptionMap[el.AnecdotesGame5Id]; !ok {
			h.anecdotesGame5OptionMap[el.AnecdotesGame5Id] = map[values.Integer]int{el.Id: i}
		} else {
			h.anecdotesGame5OptionMap[el.AnecdotesGame5Id][el.Id] = i
		}
	}
}

func (i *AnecdotesGame5Option) Len() int {
	return len(h.anecdotesGame5Option)
}

func (i *AnecdotesGame5Option) List() []AnecdotesGame5Option {
	return h.anecdotesGame5Option
}

func (i *AnecdotesGame5Option) GetAnecdotesGame5OptionById(parentId, id values.Integer) (*AnecdotesGame5Option, bool) {
	item, ok := h.anecdotesGame5OptionMap[parentId]
	if !ok {
		return nil, false
	}
	index, ok := item[id]
	if !ok {
		return nil, false
	}
	return &h.anecdotesGame5Option[index], true
}
