// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type TempBag struct {
	Id           values.Integer `mapstructure:"id" json:"id"`
	TempBagLevel values.Integer `mapstructure:"temp_bag_level" json:"temp_bag_level"`
	RoleLevel    values.Integer `mapstructure:"role_level" json:"role_level"`
	ProfitUpper  values.Integer `mapstructure:"profit_upper" json:"profit_upper"`
}

// parse func
func ParseTempBag(data *Data) {
	if err := data.UnmarshalKey("temp_bag", &h.tempBag); err != nil {
		panic(errors.New("parse table TempBag err:\n" + err.Error()))
	}
	for i, el := range h.tempBag {
		h.tempBagMap[el.Id] = i
	}
}

func (i *TempBag) Len() int {
	return len(h.tempBag)
}

func (i *TempBag) List() []TempBag {
	return h.tempBag
}

func (i *TempBag) GetTempBagById(id values.Integer) (*TempBag, bool) {
	index, ok := h.tempBagMap[id]
	if !ok {
		return nil, false
	}
	return &h.tempBag[index], true
}
