// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Shopgoodslist struct {
	Id       values.Integer   `mapstructure:"id" json:"id"`
	GoodsNum values.Integer   `mapstructure:"goods_num" json:"goods_num"`
	PlayLv   []values.Integer `mapstructure:"play_lv" json:"play_lv"`
}

// parse func
func ParseShopgoodslist(data *Data) {
	if err := data.UnmarshalKey("shopgoodslist", &h.shopgoodslist); err != nil {
		panic(errors.New("parse table Shopgoodslist err:\n" + err.Error()))
	}
	for i, el := range h.shopgoodslist {
		h.shopgoodslistMap[el.Id] = i
	}
}

func (i *Shopgoodslist) Len() int {
	return len(h.shopgoodslist)
}

func (i *Shopgoodslist) List() []Shopgoodslist {
	return h.shopgoodslist
}

func (i *Shopgoodslist) GetShopgoodslistById(id values.Integer) (*Shopgoodslist, bool) {
	index, ok := h.shopgoodslistMap[id]
	if !ok {
		return nil, false
	}
	return &h.shopgoodslist[index], true
}
