// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Dubbing struct {
	Id          values.Integer `mapstructure:"id" json:"id"`
	DubbingFile string         `mapstructure:"dubbing_file" json:"dubbing_file"`
}

// parse func
func ParseDubbing(data *Data) {
	if err := data.UnmarshalKey("dubbing", &h.dubbing); err != nil {
		panic(errors.New("parse table Dubbing err:\n" + err.Error()))
	}
	for i, el := range h.dubbing {
		h.dubbingMap[el.Id] = i
	}
}

func (i *Dubbing) Len() int {
	return len(h.dubbing)
}

func (i *Dubbing) List() []Dubbing {
	return h.dubbing
}

func (i *Dubbing) GetDubbingById(id values.Integer) (*Dubbing, bool) {
	index, ok := h.dubbingMap[id]
	if !ok {
		return nil, false
	}
	return &h.dubbing[index], true
}
