// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Timeline struct {
	Id    values.Integer `mapstructure:"id" json:"id"`
	Scene string         `mapstructure:"scene" json:"scene"`
}

// parse func
func ParseTimeline(data *Data) {
	if err := data.UnmarshalKey("timeline", &h.timeline); err != nil {
		panic(errors.New("parse table Timeline err:\n" + err.Error()))
	}
	for i, el := range h.timeline {
		h.timelineMap[el.Id] = i
	}
}

func (i *Timeline) Len() int {
	return len(h.timeline)
}

func (i *Timeline) List() []Timeline {
	return h.timeline
}

func (i *Timeline) GetTimelineById(id values.Integer) (*Timeline, bool) {
	index, ok := h.timelineMap[id]
	if !ok {
		return nil, false
	}
	return &h.timeline[index], true
}
