// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type MainCityMapNpcPath struct {
	Id            values.Integer   `mapstructure:"id" json:"id"`
	Path          string           `mapstructure:"path" json:"path"`
	SpeedInterval []values.Integer `mapstructure:"speed_interval" json:"speed_interval"`
}

// parse func
func ParseMainCityMapNpcPath(data *Data) {
	if err := data.UnmarshalKey("main_city_map_npc_path", &h.mainCityMapNpcPath); err != nil {
		panic(errors.New("parse table MainCityMapNpcPath err:\n" + err.Error()))
	}
	for i, el := range h.mainCityMapNpcPath {
		h.mainCityMapNpcPathMap[el.Id] = i
	}
}

func (i *MainCityMapNpcPath) Len() int {
	return len(h.mainCityMapNpcPath)
}

func (i *MainCityMapNpcPath) List() []MainCityMapNpcPath {
	return h.mainCityMapNpcPath
}

func (i *MainCityMapNpcPath) GetMainCityMapNpcPathById(id values.Integer) (*MainCityMapNpcPath, bool) {
	index, ok := h.mainCityMapNpcPathMap[id]
	if !ok {
		return nil, false
	}
	return &h.mainCityMapNpcPath[index], true
}
