// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type ClassAh struct {
	Id     values.Integer `mapstructure:"id" json:"id"`
	AhText string         `mapstructure:"ah_text" json:"ah_text"`
}

// parse func
func ParseClassAh(data *Data) {
	if err := data.UnmarshalKey("class_ah", &h.classAh); err != nil {
		panic(errors.New("parse table ClassAh err:\n" + err.Error()))
	}
	for i, el := range h.classAh {
		h.classAhMap[el.Id] = i
	}
}

func (i *ClassAh) Len() int {
	return len(h.classAh)
}

func (i *ClassAh) List() []ClassAh {
	return h.classAh
}

func (i *ClassAh) GetClassAhById(id values.Integer) (*ClassAh, bool) {
	index, ok := h.classAhMap[id]
	if !ok {
		return nil, false
	}
	return &h.classAh[index], true
}
