// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type GuildSign struct {
	Id      values.Integer `mapstructure:"id" json:"id"`
	SignImg string         `mapstructure:"sign_img" json:"sign_img"`
}

// parse func
func ParseGuildSign(data *Data) {
	if err := data.UnmarshalKey("guild_sign", &h.guildSign); err != nil {
		panic(errors.New("parse table GuildSign err:\n" + err.Error()))
	}
	for i, el := range h.guildSign {
		h.guildSignMap[el.Id] = i
	}
}

func (i *GuildSign) Len() int {
	return len(h.guildSign)
}

func (i *GuildSign) List() []GuildSign {
	return h.guildSign
}

func (i *GuildSign) GetGuildSignById(id values.Integer) (*GuildSign, bool) {
	index, ok := h.guildSignMap[id]
	if !ok {
		return nil, false
	}
	return &h.guildSign[index], true
}
