// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type CombatBattle struct {
	Id             values.Integer                    `mapstructure:"id" json:"id"`
	SubsectionRank []values.Integer                  `mapstructure:"subsection_rank" json:"subsection_rank"`
	RankReward     map[values.Integer]values.Integer `mapstructure:"rank_reward" json:"rank_reward"`
}

// parse func
func ParseCombatBattle(data *Data) {
	if err := data.UnmarshalKey("combat_battle", &h.combatBattle); err != nil {
		panic(errors.New("parse table CombatBattle err:\n" + err.Error()))
	}
	for i, el := range h.combatBattle {
		h.combatBattleMap[el.Id] = i
	}
}

func (i *CombatBattle) Len() int {
	return len(h.combatBattle)
}

func (i *CombatBattle) List() []CombatBattle {
	return h.combatBattle
}

func (i *CombatBattle) GetCombatBattleById(id values.Integer) (*CombatBattle, bool) {
	index, ok := h.combatBattleMap[id]
	if !ok {
		return nil, false
	}
	return &h.combatBattle[index], true
}
