// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type MainCityMap struct {
	Id                values.Integer   `mapstructure:"id" json:"id"`
	MapAddr           string           `mapstructure:"map_addr" json:"map_addr"`
	BuildingPosId     []values.Integer `mapstructure:"building_pos_id" json:"building_pos_id"`
	PathId            []values.Integer `mapstructure:"path_id" json:"path_id"`
	OtherPlayerPathId []values.Integer `mapstructure:"other_player_path_id" json:"other_player_path_id"`
}

// parse func
func ParseMainCityMap(data *Data) {
	if err := data.UnmarshalKey("main_city_map", &h.mainCityMap); err != nil {
		panic(errors.New("parse table MainCityMap err:\n" + err.Error()))
	}
	for i, el := range h.mainCityMap {
		h.mainCityMapMap[el.Id] = i
	}
}

func (i *MainCityMap) Len() int {
	return len(h.mainCityMap)
}

func (i *MainCityMap) List() []MainCityMap {
	return h.mainCityMap
}

func (i *MainCityMap) GetMainCityMapById(id values.Integer) (*MainCityMap, bool) {
	index, ok := h.mainCityMapMap[id]
	if !ok {
		return nil, false
	}
	return &h.mainCityMap[index], true
}
