// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type GuildBoss struct {
	Id       values.Integer                    `mapstructure:"id" json:"id"`
	Hp       values.Integer                    `mapstructure:"hp" json:"hp"`
	HpReward map[values.Integer]values.Integer `mapstructure:"hp_reward" json:"hp_reward"`
}

// parse func
func ParseGuildBoss(data *Data) {
	if err := data.UnmarshalKey("guild_boss", &h.guildBoss); err != nil {
		panic(errors.New("parse table GuildBoss err:\n" + err.Error()))
	}
	for i, el := range h.guildBoss {
		h.guildBossMap[el.Id] = i
	}
}

func (i *GuildBoss) Len() int {
	return len(h.guildBoss)
}

func (i *GuildBoss) List() []GuildBoss {
	return h.guildBoss
}

func (i *GuildBoss) GetGuildBossById(id values.Integer) (*GuildBoss, bool) {
	index, ok := h.guildBossMap[id]
	if !ok {
		return nil, false
	}
	return &h.guildBoss[index], true
}
