// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Drop struct {
	Id   values.Integer `mapstructure:"id" json:"id"`
	Desc string         `mapstructure:"desc" json:"desc"`
}

// parse func
func ParseDrop(data *Data) {
	if err := data.UnmarshalKey("drop", &h.drop); err != nil {
		panic(errors.New("parse table Drop err:\n" + err.Error()))
	}
	for i, el := range h.drop {
		h.dropMap[el.Id] = i
	}
}

func (i *Drop) Len() int {
	return len(h.drop)
}

func (i *Drop) List() []Drop {
	return h.drop
}

func (i *Drop) GetDropById(id values.Integer) (*Drop, bool) {
	index, ok := h.dropMap[id]
	if !ok {
		return nil, false
	}
	return &h.drop[index], true
}
