// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type AnecdotesGame4 struct {
	Id     values.Integer `mapstructure:"id" json:"id"`
	GameLv values.Integer `mapstructure:"game_lv" json:"game_lv"`
	Weight values.Integer `mapstructure:"weight" json:"weight"`
}

// parse func
func ParseAnecdotesGame4(data *Data) {
	if err := data.UnmarshalKey("anecdotes_game4", &h.anecdotesGame4); err != nil {
		panic(errors.New("parse table AnecdotesGame4 err:\n" + err.Error()))
	}
	for i, el := range h.anecdotesGame4 {
		h.anecdotesGame4Map[el.Id] = i
	}
}

func (i *AnecdotesGame4) Len() int {
	return len(h.anecdotesGame4)
}

func (i *AnecdotesGame4) List() []AnecdotesGame4 {
	return h.anecdotesGame4
}

func (i *AnecdotesGame4) GetAnecdotesGame4ById(id values.Integer) (*AnecdotesGame4, bool) {
	index, ok := h.anecdotesGame4Map[id]
	if !ok {
		return nil, false
	}
	return &h.anecdotesGame4[index], true
}
