// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type RelicsLv struct {
	Id values.Integer `mapstructure:"id" json:"id"`
}

// parse func
func ParseRelicsLv(data *Data) {
	if err := data.UnmarshalKey("relics_lv", &h.relicsLv); err != nil {
		panic(errors.New("parse table RelicsLv err:\n" + err.Error()))
	}
	for i, el := range h.relicsLv {
		h.relicsLvMap[el.Id] = i
	}
}

func (i *RelicsLv) Len() int {
	return len(h.relicsLv)
}

func (i *RelicsLv) List() []RelicsLv {
	return h.relicsLv
}

func (i *RelicsLv) GetRelicsLvById(id values.Integer) (*RelicsLv, bool) {
	index, ok := h.relicsLvMap[id]
	if !ok {
		return nil, false
	}
	return &h.relicsLv[index], true
}
