// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type PersonalBossBuff struct {
	Id         values.Integer `mapstructure:"id" json:"id"`
	BossBuffId values.Integer `mapstructure:"boss_buff_id" json:"boss_buff_id"`
}

// parse func
func ParsePersonalBossBuff(data *Data) {
	if err := data.UnmarshalKey("personal_boss_buff", &h.personalBossBuff); err != nil {
		panic(errors.New("parse table PersonalBossBuff err:\n" + err.Error()))
	}
	for i, el := range h.personalBossBuff {
		h.personalBossBuffMap[el.Id] = i
	}
}

func (i *PersonalBossBuff) Len() int {
	return len(h.personalBossBuff)
}

func (i *PersonalBossBuff) List() []PersonalBossBuff {
	return h.personalBossBuff
}

func (i *PersonalBossBuff) GetPersonalBossBuffById(id values.Integer) (*PersonalBossBuff, bool) {
	index, ok := h.personalBossBuffMap[id]
	if !ok {
		return nil, false
	}
	return &h.personalBossBuff[index], true
}
