// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type AnecdotesGame5 struct {
	Id     values.Integer `mapstructure:"id" json:"id"`
	GameLv values.Integer `mapstructure:"game_lv" json:"game_lv"`
	Weight values.Integer `mapstructure:"weight" json:"weight"`
}

// parse func
func ParseAnecdotesGame5(data *Data) {
	if err := data.UnmarshalKey("anecdotes_game5", &h.anecdotesGame5); err != nil {
		panic(errors.New("parse table AnecdotesGame5 err:\n" + err.Error()))
	}
	for i, el := range h.anecdotesGame5 {
		h.anecdotesGame5Map[el.Id] = i
	}
}

func (i *AnecdotesGame5) Len() int {
	return len(h.anecdotesGame5)
}

func (i *AnecdotesGame5) List() []AnecdotesGame5 {
	return h.anecdotesGame5
}

func (i *AnecdotesGame5) GetAnecdotesGame5ById(id values.Integer) (*AnecdotesGame5, bool) {
	index, ok := h.anecdotesGame5Map[id]
	if !ok {
		return nil, false
	}
	return &h.anecdotesGame5[index], true
}
