// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type AnecdotesGame1 struct {
	Id        values.Integer                    `mapstructure:"id" json:"id"`
	Name      string                            `mapstructure:"name" json:"name"`
	StoryText []string                          `mapstructure:"story_text" json:"story_text"`
	ChestImg  string                            `mapstructure:"chest_img" json:"chest_img"`
	GameLv    values.Integer                    `mapstructure:"game_lv" json:"game_lv"`
	Weight    values.Integer                    `mapstructure:"weight" json:"weight"`
	Reward    map[values.Integer]values.Integer `mapstructure:"reward" json:"reward"`
}

// parse func
func ParseAnecdotesGame1(data *Data) {
	if err := data.UnmarshalKey("anecdotes_game1", &h.anecdotesGame1); err != nil {
		panic(errors.New("parse table AnecdotesGame1 err:\n" + err.Error()))
	}
	for i, el := range h.anecdotesGame1 {
		h.anecdotesGame1Map[el.Id] = i
	}
}

func (i *AnecdotesGame1) Len() int {
	return len(h.anecdotesGame1)
}

func (i *AnecdotesGame1) List() []AnecdotesGame1 {
	return h.anecdotesGame1
}

func (i *AnecdotesGame1) GetAnecdotesGame1ById(id values.Integer) (*AnecdotesGame1, bool) {
	index, ok := h.anecdotesGame1Map[id]
	if !ok {
		return nil, false
	}
	return &h.anecdotesGame1[index], true
}
