// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Bag struct {
	Id         values.Integer `mapstructure:"id" json:"id"`
	AddBagTime values.Integer `mapstructure:"add_bag_time" json:"add_bag_time"`
}

// parse func
func ParseBag(data *Data) {
	if err := data.UnmarshalKey("bag", &h.bag); err != nil {
		panic(errors.New("parse table Bag err:\n" + err.Error()))
	}
	for i, el := range h.bag {
		h.bagMap[el.Id] = i
	}
}

func (i *Bag) Len() int {
	return len(h.bag)
}

func (i *Bag) List() []Bag {
	return h.bag
}

func (i *Bag) GetBagById(id values.Integer) (*Bag, bool) {
	index, ok := h.bagMap[id]
	if !ok {
		return nil, false
	}
	return &h.bag[index], true
}
