// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Gift struct {
	Id   values.Integer `mapstructure:"id" json:"id"`
	Name string         `mapstructure:"name" json:"name"`
	Num  values.Integer `mapstructure:"num" json:"num"`
}

// parse func
func ParseGift(data *Data) {
	if err := data.UnmarshalKey("gift", &h.gift); err != nil {
		panic(errors.New("parse table Gift err:\n" + err.Error()))
	}
	for i, el := range h.gift {
		h.giftMap[el.Id] = i
	}
}

func (i *Gift) Len() int {
	return len(h.gift)
}

func (i *Gift) List() []Gift {
	return h.gift
}

func (i *Gift) GetGiftById(id values.Integer) (*Gift, bool) {
	index, ok := h.giftMap[id]
	if !ok {
		return nil, false
	}
	return &h.gift[index], true
}
