// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type GuildGvghelp struct {
	Id          values.Integer `mapstructure:"id" json:"id"`
	Typ         values.Integer `mapstructure:"typ" json:"typ"`
	TextId      string         `mapstructure:"text_id" json:"text_id"`
	ContentText string         `mapstructure:"content_text" json:"content_text"`
	ContendId   values.Integer `mapstructure:"contend_id" json:"contend_id"`
}

// parse func
func ParseGuildGvghelp(data *Data) {
	if err := data.UnmarshalKey("guild_gvghelp", &h.guildGvghelp); err != nil {
		panic(errors.New("parse table GuildGvghelp err:\n" + err.Error()))
	}
	for i, el := range h.guildGvghelp {
		h.guildGvghelpMap[el.Id] = i
	}
}

func (i *GuildGvghelp) Len() int {
	return len(h.guildGvghelp)
}

func (i *GuildGvghelp) List() []GuildGvghelp {
	return h.guildGvghelp
}

func (i *GuildGvghelp) GetGuildGvghelpById(id values.Integer) (*GuildGvghelp, bool) {
	index, ok := h.guildGvghelpMap[id]
	if !ok {
		return nil, false
	}
	return &h.guildGvghelp[index], true
}
