// Code generated by exporter. DO NOT EDIT.
package rule_model

import "coin-server/common/values"

var h = newHolder()

type holder struct {
	version                          string
	pvPRankReward                    []PvPRankReward
	pvPRankRewardMap                 map[values.Integer]int
	pvPRobot                         []PvPRobot
	pvPRobotMap                      map[values.Integer]int
	achievement                      []Achievement
	achievementMap                   map[values.Integer]int
	achievementList                  []AchievementList
	achievementListMap               map[values.Integer]map[values.Integer]int
	achievementTotal                 []AchievementTotal
	achievementTotalMap              map[values.Integer]int
	actionfusion                     []Actionfusion
	actionfusionMap                  map[values.Integer]int
	activity                         []Activity
	activityMap                      map[values.Integer]int
	activity0yuanpurchase            []Activity0yuanpurchase
	activity0yuanpurchaseMap         map[values.Integer]int
	activityXdaygoal                 []ActivityXdaygoal
	activityXdaygoalMap              map[values.Integer]int
	activityXdaygoalScorereward      []ActivityXdaygoalScorereward
	activityXdaygoalScorerewardMap   map[values.Integer]int
	activityAccumulatedrecharge      []ActivityAccumulatedrecharge
	activityAccumulatedrechargeMap   map[values.Integer]int
	activityCircular                 []ActivityCircular
	activityCircularMap              map[values.Integer]int
	activityDailygiftBuy             []ActivityDailygiftBuy
	activityDailygiftBuyMap          map[values.Integer]int
	activityFirstpay                 []ActivityFirstpay
	activityFirstpayMap              map[values.Integer]int
	activityGrowthfund               []ActivityGrowthfund
	activityGrowthfundMap            map[values.Integer]int
	activityLimitedtimePackage       []ActivityLimitedtimePackage
	activityLimitedtimePackageMap    map[values.Integer]int
	activityLimitedtimePackagePay    []ActivityLimitedtimePackagePay
	activityLimitedtimePackagePayMap map[values.Integer]map[values.Integer]int
	activityLoginReward              []ActivityLoginReward
	activityLoginRewardMap           map[values.Integer]int
	activityMonthlycard              []ActivityMonthlycard
	activityMonthlycardMap           map[values.Integer]int
	activityPassesAwards             []ActivityPassesAwards
	activityPassesAwardsMap          map[values.Integer]int
	activityReward                   []ActivityReward
	activityRewardMap                map[values.Integer]int
	activityStellargemShopmall       []ActivityStellargemShopmall
	activityStellargemShopmallMap    map[values.Integer]int
	activityWeekly                   []ActivityWeekly
	activityWeeklyMap                map[values.Integer]int
	activityWeeklyCastsword          []ActivityWeeklyCastsword
	activityWeeklyCastswordMap       map[values.Integer]int
	activityWeeklyChallenge          []ActivityWeeklyChallenge
	activityWeeklyChallengeMap       map[values.Integer]int
	activityWeeklyExchange           []ActivityWeeklyExchange
	activityWeeklyExchangeMap        map[values.Integer]int
	activityWeeklyGift               []ActivityWeeklyGift
	activityWeeklyGiftMap            map[values.Integer]int
	activityWeeklyRank               []ActivityWeeklyRank
	activityWeeklyRankMap            map[values.Integer]int
	anecdotes                        []Anecdotes
	anecdotesMap                     map[values.Integer]int
	anecdotesClassText               []AnecdotesClassText
	anecdotesClassTextMap            map[values.Integer]map[values.Integer]int
	anecdotesGame1                   []AnecdotesGame1
	anecdotesGame1Map                map[values.Integer]int
	anecdotesGame1Option             []AnecdotesGame1Option
	anecdotesGame1OptionMap          map[values.Integer]map[values.Integer]int
	anecdotesGame11                  []AnecdotesGame11
	anecdotesGame11Map               map[values.Integer]int
	anecdotesGame2                   []AnecdotesGame2
	anecdotesGame2Map                map[values.Integer]int
	anecdotesGame3                   []AnecdotesGame3
	anecdotesGame3Map                map[values.Integer]int
	anecdotesGame3Option             []AnecdotesGame3Option
	anecdotesGame3OptionMap          map[values.Integer]map[values.Integer]int
	anecdotesGame4                   []AnecdotesGame4
	anecdotesGame4Map                map[values.Integer]int
	anecdotesGame4Option             []AnecdotesGame4Option
	anecdotesGame4OptionMap          map[values.Integer]map[values.Integer]int
	anecdotesGame5                   []AnecdotesGame5
	anecdotesGame5Map                map[values.Integer]int
	anecdotesGame5Option             []AnecdotesGame5Option
	anecdotesGame5OptionMap          map[values.Integer]map[values.Integer]int
	anecdotesGame7                   []AnecdotesGame7
	anecdotesGame7Map                map[values.Integer]int
	anecdotesGame7Option             []AnecdotesGame7Option
	anecdotesGame7OptionMap          map[values.Integer]map[values.Integer]int
	anecdotesGame8                   []AnecdotesGame8
	anecdotesGame8Map                map[values.Integer]int
	anecdotesGame8Option             []AnecdotesGame8Option
	anecdotesGame8OptionMap          map[values.Integer]map[values.Integer]int
	anecdotesGames                   []AnecdotesGames
	anecdotesGamesMap                map[values.Integer]int
	anecdotesReward                  []AnecdotesReward
	anecdotesRewardMap               map[values.Integer]int
	announcement                     []Announcement
	announcementMap                  map[values.Integer]int
	atlas                            []Atlas
	atlasMap                         map[values.Integer]int
	atlasItem                        []AtlasItem
	atlasItemMap                     map[values.Integer]map[values.Integer]int
	attr                             []Attr
	attrMap                          map[values.Integer]int
	attrTrans                        []AttrTrans
	attrTransMap                     map[values.Integer]int
	autoWindow                       []AutoWindow
	autoWindowMap                    map[values.Integer]int
	bag                              []Bag
	bagMap                           map[values.Integer]int
	banner                           []Banner
	bannerMap                        map[values.Integer]int
	beStronger                       []BeStronger
	beStrongerMap                    map[values.Integer]int
	begining                         []Begining
	beginingMap                      map[values.Integer]int
	biography                        []Biography
	biographyMap                     map[values.Integer]int
	bossHall                         []BossHall
	bossHallMap                      map[values.Integer]int
	buff                             []Buff
	buffMap                          map[values.Integer]int
	buffEffect                       []BuffEffect
	buffEffectMap                    map[values.Integer]int
	buffEffectShow                   []BuffEffectShow
	buffEffectShowMap                map[values.Integer]int
	buffLogic                        []BuffLogic
	buffLogicMap                     map[values.Integer]int
	charge                           []Charge
	chargeMap                        map[values.Integer]int
	classAh                          []ClassAh
	classAhMap                       map[values.Integer]int
	combatBattle                     []CombatBattle
	combatBattleMap                  map[values.Integer]int
	divination                       []Divination
	divinationMap                    map[values.Integer]int
	drop                             []Drop
	dropMap                          map[values.Integer]int
	dropMini                         []DropMini
	dropMiniMap                      map[values.Integer]map[values.Integer]int
	dropLists                        []DropLists
	dropListsMap                     map[values.Integer]int
	dropListsMini                    []DropListsMini
	dropListsMiniMap                 map[values.Integer]map[values.Integer]int
	dubbing                          []Dubbing
	dubbingMap                       map[values.Integer]int
	dungeon                          []Dungeon
	dungeonMap                       map[values.Integer]int
	effect                           []Effect
	effectMap                        map[values.Integer]int
	emoji                            []Emoji
	emojiMap                         map[values.Integer]int
	enchantments                     []Enchantments
	enchantmentsMap                  map[values.Integer]int
	entrySkill                       []EntrySkill
	entrySkillMap                    map[values.Integer]int
	equip                            []Equip
	equipMap                         map[values.Integer]int
	equipComplete                    []EquipComplete
	equipCompleteMap                 map[values.Integer]int
	equipEntry                       []EquipEntry
	equipEntryMap                    map[values.Integer]int
	equipLight                       []EquipLight
	equipLightMap                    map[values.Integer]int
	equipQuality                     []EquipQuality
	equipQualityMap                  map[values.Integer]int
	equipRefine                      []EquipRefine
	equipRefineMap                   map[values.Integer]int
	equipResonance                   []EquipResonance
	equipResonanceMap                map[values.Integer]int
	equipSlot                        []EquipSlot
	equipSlotMap                     map[values.Integer]int
	equipStar                        []EquipStar
	equipStarMap                     map[values.Integer]int
	equipType                        []EquipType
	equipTypeMap                     map[values.Integer]int
	equipment                        []Equipment
	equipmentMap                     map[values.Integer]int
	exchange                         []Exchange
	exchangeMap                      map[values.Integer]int
	exchangeItem                     []ExchangeItem
	exchangeItemMap                  map[values.Integer]map[values.Integer]int
	expSkip                          []ExpSkip
	expSkipMap                       map[values.Integer]int
	expedition                       []Expedition
	expeditionMap                    map[values.Integer]int
	expeditionReward                 []ExpeditionReward
	expeditionRewardMap              map[values.Integer]map[values.Integer]int
	expeditionQuantity               []ExpeditionQuantity
	expeditionQuantityMap            map[values.Integer]int
	failureToStronger                []FailureToStronger
	failureToStrongerMap             map[values.Integer]int
	fashion                          []Fashion
	fashionMap                       map[values.Integer]int
	fashionActivate                  []FashionActivate
	fashionActivateMap               map[values.Integer]int
	fightingCapacity                 []FightingCapacity
	fightingCapacityMap              map[values.Integer]int
	flynum                           []Flynum
	flynumMap                        map[values.Integer]int
	forgeFixedRecipe                 []ForgeFixedRecipe
	forgeFixedRecipeMap              map[values.Integer]int
	forgeLevel                       []ForgeLevel
	forgeLevelMap                    map[values.Integer]int
	forgeSupplement                  []ForgeSupplement
	forgeSupplementMap               map[values.Integer]int
	gacha                            []Gacha
	gachaMap                         map[values.Integer]int
	gachalist                        []Gachalist
	gachalistMap                     map[values.Integer]map[values.Integer]int
	gift                             []Gift
	giftMap                          map[values.Integer]int
	giftItem                         []GiftItem
	giftItemMap                      map[values.Integer]map[values.Integer]int
	guideProcess                     []GuideProcess
	guideProcessMap                  map[values.Integer]int
	guideStep                        []GuideStep
	guideStepMap                     map[values.Integer]map[values.Integer]int
	guild                            []Guild
	guildMap                         map[values.Integer]int
	guildJournal                     []GuildJournal
	guildJournalMap                  map[values.Integer]int
	guildContend                     []GuildContend
	guildContendMap                  map[values.Integer]int
	guildContendbuild                []GuildContendbuild
	guildContendbuildMap             map[values.Integer]int
	guildIntegral                    []GuildIntegral
	guildIntegralMap                 map[values.Integer]int
	guildBlessing                    []GuildBlessing
	guildBlessingMap                 map[values.Integer]int
	guildBoss                        []GuildBoss
	guildBossMap                     map[values.Integer]int
	guildFunction                    []GuildFunction
	guildFunctionMap                 map[values.Integer]int
	guildGvghelp                     []GuildGvghelp
	guildGvghelpMap                  map[values.Integer]int
	guildPosition                    []GuildPosition
	guildPositionMap                 map[values.Integer]int
	guildSign                        []GuildSign
	guildSignMap                     map[values.Integer]int
	guilde                           []Guilde
	guildeMap                        map[values.Integer]int
	headSculpture                    []HeadSculpture
	headSculptureMap                 map[values.Integer]int
	headSpeak                        []HeadSpeak
	headSpeakMap                     map[values.Integer]int
	headSpeakWord                    []HeadSpeakWord
	headSpeakWordMap                 map[values.Integer]map[values.Integer]int
	headTalkBubble                   []HeadTalkBubble
	headTalkBubbleMap                map[values.Integer]int
	hero                             []Hero
	heroMap                          map[values.Integer]int
	heroDeviationEntry               []HeroDeviationEntry
	heroDeviationEntryMap            map[values.Integer]int
	homeAvatar                       []HomeAvatar
	homeAvatarMap                    map[values.Integer]int
	imageDisplayLocation             []ImageDisplayLocation
	imageDisplayLocationMap          map[values.Integer]int
	imgLanguage                      []ImgLanguage
	imgLanguageMap                   map[values.Integer]int
	inhibitAtk                       []InhibitAtk
	inhibitAtkMap                    map[values.Integer]int
	item                             []Item
	itemMap                          map[values.Integer]int
	itemClass                        []ItemClass
	itemClassMap                     map[values.Integer]int
	itemTypeIcon                     []ItemTypeIcon
	itemTypeIconMap                  map[values.Integer]int
	journeyChest                     []JourneyChest
	journeyChestMap                  map[values.Integer]int
	journeyList                      []JourneyList
	journeyListMap                   map[values.Integer]int
	keyValue                         []KeyValue
	languageBackend                  []LanguageBackend
	languageBackendMap               map[values.Integer]int
	looptask                         []Looptask
	looptaskMap                      map[values.Integer]int
	loopTaskStageReward              []LoopTaskStageReward
	loopTaskStageRewardMap           map[values.Integer]int
	mail                             []Mail
	mailMap                          map[values.Integer]int
	mainCityMap                      []MainCityMap
	mainCityMapMap                   map[values.Integer]int
	mainCityMapBuilding              []MainCityMapBuilding
	mainCityMapBuildingMap           map[values.Integer]int
	mainCityMapNpcPath               []MainCityMapNpcPath
	mainCityMapNpcPathMap            map[values.Integer]int
	mainTask                         []MainTask
	mainTaskMap                      map[values.Integer]int
	mainTaskChapter                  []MainTaskChapter
	mainTaskChapterMap               map[values.Integer]int
	mainTaskChapterReward            []MainTaskChapterReward
	mainTaskChapterRewardMap         map[values.Integer]map[values.Integer]int
	mainTaskChapterTarget            []MainTaskChapterTarget
	mainTaskChapterTargetMap         map[values.Integer]int
	mapBuilding                      []MapBuilding
	mapBuildingMap                   map[values.Integer]int
	mapNpc                           []MapNpc
	mapNpcMap                        map[values.Integer]int
	mapNpcWithMainStory              []MapNpcWithMainStory
	mapNpcWithMainStoryMap           map[values.Integer]map[values.Integer]int
	mapRelation                      []MapRelation
	mapRelationMap                   map[values.Integer]int
	mapScene                         []MapScene
	mapSceneMap                      map[values.Integer]int
	mapSelect                        []MapSelect
	mapSelectMap                     map[values.Integer]int
	mapTransmit                      []MapTransmit
	mapTransmitMap                   map[values.Integer]int
	mechanics                        []Mechanics
	mechanicsMap                     map[values.Integer]int
	medicament                       []Medicament
	medicamentMap                    map[values.Integer]int
	monster                          []Monster
	monsterMap                       map[values.Integer]int
	monsterAttr                      []MonsterAttr
	monsterAttrMap                   map[values.Integer]int
	monsterGroup                     []MonsterGroup
	monsterGroupMap                  map[values.Integer]int
	notice                           []Notice
	noticeMap                        map[values.Integer]int
	npcChallengeDungeon              []NpcChallengeDungeon
	npcChallengeDungeonMap           map[values.Integer]int
	npcDialogue                      []NpcDialogue
	npcDialogueMap                   map[values.Integer]int
	dialogueWord                     []DialogueWord
	dialogueWordMap                  map[values.Integer]map[values.Integer]int
	dialogueOpt                      []DialogueOpt
	dialogueOptMap                   map[values.Integer]map[values.Integer]int
	npcTask                          []NpcTask
	npcTaskMap                       map[values.Integer]int
	optionalBox                      []OptionalBox
	optionalBoxMap                   map[values.Integer]int
	personalBossBuff                 []PersonalBossBuff
	personalBossBuffMap              map[values.Integer]int
	personalBossHelpPointsReward     []PersonalBossHelpPointsReward
	personalBossHelpPointsRewardMap  map[values.Integer]int
	personalBossHelperCards          []PersonalBossHelperCards
	personalBossHelperCardsMap       map[values.Integer]int
	personalBossLibrary              []PersonalBossLibrary
	personalBossLibraryMap           map[values.Integer]int
	personalBossNumberFloor          []PersonalBossNumberFloor
	personalBossNumberFloorMap       map[values.Integer]int
	personalBossLv                   []PersonalBossLv
	personalBossLvMap                map[values.Integer]map[values.Integer]int
	personalBossPassingReward        []PersonalBossPassingReward
	personalBossPassingRewardMap     map[values.Integer]int
	planeDungeon                     []PlaneDungeon
	planeDungeonMap                  map[values.Integer]int
	popup                            []Popup
	popupMap                         map[values.Integer]int
	quality                          []Quality
	qualityMap                       map[values.Integer]int
	recycleType                      []RecycleType
	recycleTypeMap                   map[values.Integer]int
	relics                           []Relics
	relicsMap                        map[values.Integer]int
	relicsFunctionAttr               []RelicsFunctionAttr
	relicsFunctionAttrMap            map[values.Integer]int
	relicsLv                         []RelicsLv
	relicsLvMap                      map[values.Integer]int
	relicsLvQuality                  []RelicsLvQuality
	relicsLvQualityMap               map[values.Integer]map[values.Integer]int
	relicsSkill                      []RelicsSkill
	relicsSkillMap                   map[values.Integer]int
	relicsSkilltype                  []RelicsSkilltype
	relicsSkilltypeMap               map[values.Integer]int
	robot                            []Robot
	robotMap                         map[values.Integer]int
	robotName                        []RobotName
	robotNameMap                     map[values.Integer]int
	roguelikeArtifact1               []RoguelikeArtifact1
	roguelikeArtifact1Map            map[values.Integer]int
	roguelikeArtifact2               []RoguelikeArtifact2
	roguelikeArtifact2Map            map[values.Integer]int
	roguelikeArtifact3               []RoguelikeArtifact3
	roguelikeArtifact3Map            map[values.Integer]int
	roguelikeDungeon                 []RoguelikeDungeon
	roguelikeDungeonMap              map[values.Integer]int
	roguelikeDungeonRoom             []RoguelikeDungeonRoom
	roguelikeDungeonRoomMap          map[values.Integer]map[values.Integer]int
	roguelikeEntry                   []RoguelikeEntry
	roguelikeEntryMap                map[values.Integer]int
	roleChangemodel                  []RoleChangemodel
	roleChangemodelMap               map[values.Integer]int
	roleLv                           []RoleLv
	roleLvMap                        map[values.Integer]int
	roleLvTitle                      []RoleLvTitle
	roleLvTitleMap                   map[values.Integer]int
	roleReachDungeon                 []RoleReachDungeon
	roleReachDungeonMap              map[values.Integer]int
	roleReachItem                    []RoleReachItem
	roleReachItemMap                 map[values.Integer]int
	roleSkill                        []RoleSkill
	roleSkillMap                     map[values.Integer]int
	skillLv                          []SkillLv
	skillLvMap                       map[values.Integer]map[values.Integer]int
	rowHero                          []RowHero
	rowHeroMap                       map[values.Integer]int
	sample                           []Sample
	sampleMap                        map[values.Integer]int
	sampleChild1                     []SampleChild1
	sampleChild1Map                  map[values.Integer]map[values.Integer]int
	sampleChild2                     []SampleChild2
	sampleChild2Map                  map[values.Integer]map[values.Integer]int
	sensitiveDict1                   []SensitiveDict1
	sensitiveDict1Map                map[values.Integer]int
	sensitiveDict2                   []SensitiveDict2
	sensitiveDict2Map                map[values.Integer]int
	shieldedWord                     []ShieldedWord
	shieldedWordMap                  map[values.Integer]int
	shopgoodslist                    []Shopgoodslist
	shopgoodslistMap                 map[values.Integer]int
	goodslistLv                      []GoodslistLv
	goodslistLvMap                   map[values.Integer]map[values.Integer]int
	sideSysEntry                     []SideSysEntry
	sideSysEntryMap                  map[values.Integer]int
	skill                            []Skill
	skillMap                         map[values.Integer]int
	skillPos                         []SkillPos
	skillPosMap                      map[values.Integer]int
	skillstone                       []Skillstone
	skillstoneMap                    map[values.Integer]int
	soulContract                     []SoulContract
	soulContractMap                  map[values.Integer]int
	specialResBar                    []SpecialResBar
	specialResBarMap                 map[values.Integer]int
	storyIllustration                []StoryIllustration
	storyIllustrationMap             map[values.Integer]int
	stringCn                         []StringCn
	stringCnMap                      map[values.Integer]int
	stringEn                         []StringEn
	stringEnMap                      map[values.Integer]map[values.Integer]int
	summoned                         []Summoned
	summonedMap                      map[values.Integer]int
	system                           []System
	systemMap                        map[values.Integer]int
	systemUnlockCondition            []SystemUnlockCondition
	systemUnlockConditionMap         map[values.Integer]int
	talent                           []Talent
	talentMap                        map[values.Integer]int
	talentAttr                       []TalentAttr
	talentAttrMap                    map[values.Integer]int
	talentplate                      []Talentplate
	talentplateMap                   map[values.Integer]int
	targetTask                       []TargetTask
	targetTaskMap                    map[values.Integer]int
	targetTaskStage                  []TargetTaskStage
	targetTaskStageMap               map[values.Integer]map[values.Integer]int
	taskType                         []TaskType
	taskTypeMap                      map[values.Integer]int
	tempBag                          []TempBag
	tempBagMap                       map[values.Integer]int
	testBattle                       []TestBattle
	testBattleMap                    map[values.Integer]int
	timeline                         []Timeline
	timelineMap                      map[values.Integer]int
	towerDefault                     []TowerDefault
	towerDefaultMap                  map[values.Integer]int
	verifyLanguage                   []VerifyLanguage
	verifyLanguageMap                map[values.Integer]int
}

func newHolder() holder {
	return holder{
		pvPRankRewardMap:                 make(map[values.Integer]int, 256),
		pvPRobotMap:                      make(map[values.Integer]int, 256),
		achievementMap:                   make(map[values.Integer]int, 256),
		achievementListMap:               make(map[values.Integer]map[values.Integer]int, 256),
		achievementTotalMap:              make(map[values.Integer]int, 256),
		actionfusionMap:                  make(map[values.Integer]int, 256),
		activityMap:                      make(map[values.Integer]int, 256),
		activity0yuanpurchaseMap:         make(map[values.Integer]int, 256),
		activityXdaygoalMap:              make(map[values.Integer]int, 256),
		activityXdaygoalScorerewardMap:   make(map[values.Integer]int, 256),
		activityAccumulatedrechargeMap:   make(map[values.Integer]int, 256),
		activityCircularMap:              make(map[values.Integer]int, 256),
		activityDailygiftBuyMap:          make(map[values.Integer]int, 256),
		activityFirstpayMap:              make(map[values.Integer]int, 256),
		activityGrowthfundMap:            make(map[values.Integer]int, 256),
		activityLimitedtimePackageMap:    make(map[values.Integer]int, 256),
		activityLimitedtimePackagePayMap: make(map[values.Integer]map[values.Integer]int, 256),
		activityLoginRewardMap:           make(map[values.Integer]int, 256),
		activityMonthlycardMap:           make(map[values.Integer]int, 256),
		activityPassesAwardsMap:          make(map[values.Integer]int, 256),
		activityRewardMap:                make(map[values.Integer]int, 256),
		activityStellargemShopmallMap:    make(map[values.Integer]int, 256),
		activityWeeklyMap:                make(map[values.Integer]int, 256),
		activityWeeklyCastswordMap:       make(map[values.Integer]int, 256),
		activityWeeklyChallengeMap:       make(map[values.Integer]int, 256),
		activityWeeklyExchangeMap:        make(map[values.Integer]int, 256),
		activityWeeklyGiftMap:            make(map[values.Integer]int, 256),
		activityWeeklyRankMap:            make(map[values.Integer]int, 256),
		anecdotesMap:                     make(map[values.Integer]int, 256),
		anecdotesClassTextMap:            make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGame1Map:                make(map[values.Integer]int, 256),
		anecdotesGame1OptionMap:          make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGame11Map:               make(map[values.Integer]int, 256),
		anecdotesGame2Map:                make(map[values.Integer]int, 256),
		anecdotesGame3Map:                make(map[values.Integer]int, 256),
		anecdotesGame3OptionMap:          make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGame4Map:                make(map[values.Integer]int, 256),
		anecdotesGame4OptionMap:          make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGame5Map:                make(map[values.Integer]int, 256),
		anecdotesGame5OptionMap:          make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGame7Map:                make(map[values.Integer]int, 256),
		anecdotesGame7OptionMap:          make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGame8Map:                make(map[values.Integer]int, 256),
		anecdotesGame8OptionMap:          make(map[values.Integer]map[values.Integer]int, 256),
		anecdotesGamesMap:                make(map[values.Integer]int, 256),
		anecdotesRewardMap:               make(map[values.Integer]int, 256),
		announcementMap:                  make(map[values.Integer]int, 256),
		atlasMap:                         make(map[values.Integer]int, 256),
		atlasItemMap:                     make(map[values.Integer]map[values.Integer]int, 256),
		attrMap:                          make(map[values.Integer]int, 256),
		attrTransMap:                     make(map[values.Integer]int, 256),
		autoWindowMap:                    make(map[values.Integer]int, 256),
		bagMap:                           make(map[values.Integer]int, 256),
		bannerMap:                        make(map[values.Integer]int, 256),
		beStrongerMap:                    make(map[values.Integer]int, 256),
		beginingMap:                      make(map[values.Integer]int, 256),
		biographyMap:                     make(map[values.Integer]int, 256),
		bossHallMap:                      make(map[values.Integer]int, 256),
		buffMap:                          make(map[values.Integer]int, 256),
		buffEffectMap:                    make(map[values.Integer]int, 256),
		buffEffectShowMap:                make(map[values.Integer]int, 256),
		buffLogicMap:                     make(map[values.Integer]int, 256),
		chargeMap:                        make(map[values.Integer]int, 256),
		classAhMap:                       make(map[values.Integer]int, 256),
		combatBattleMap:                  make(map[values.Integer]int, 256),
		divinationMap:                    make(map[values.Integer]int, 256),
		dropMap:                          make(map[values.Integer]int, 256),
		dropMiniMap:                      make(map[values.Integer]map[values.Integer]int, 256),
		dropListsMap:                     make(map[values.Integer]int, 256),
		dropListsMiniMap:                 make(map[values.Integer]map[values.Integer]int, 256),
		dubbingMap:                       make(map[values.Integer]int, 256),
		dungeonMap:                       make(map[values.Integer]int, 256),
		effectMap:                        make(map[values.Integer]int, 256),
		emojiMap:                         make(map[values.Integer]int, 256),
		enchantmentsMap:                  make(map[values.Integer]int, 256),
		entrySkillMap:                    make(map[values.Integer]int, 256),
		equipMap:                         make(map[values.Integer]int, 256),
		equipCompleteMap:                 make(map[values.Integer]int, 256),
		equipEntryMap:                    make(map[values.Integer]int, 256),
		equipLightMap:                    make(map[values.Integer]int, 256),
		equipQualityMap:                  make(map[values.Integer]int, 256),
		equipRefineMap:                   make(map[values.Integer]int, 256),
		equipResonanceMap:                make(map[values.Integer]int, 256),
		equipSlotMap:                     make(map[values.Integer]int, 256),
		equipStarMap:                     make(map[values.Integer]int, 256),
		equipTypeMap:                     make(map[values.Integer]int, 256),
		equipmentMap:                     make(map[values.Integer]int, 256),
		exchangeMap:                      make(map[values.Integer]int, 256),
		exchangeItemMap:                  make(map[values.Integer]map[values.Integer]int, 256),
		expSkipMap:                       make(map[values.Integer]int, 256),
		expeditionMap:                    make(map[values.Integer]int, 256),
		expeditionRewardMap:              make(map[values.Integer]map[values.Integer]int, 256),
		expeditionQuantityMap:            make(map[values.Integer]int, 256),
		failureToStrongerMap:             make(map[values.Integer]int, 256),
		fashionMap:                       make(map[values.Integer]int, 256),
		fashionActivateMap:               make(map[values.Integer]int, 256),
		fightingCapacityMap:              make(map[values.Integer]int, 256),
		flynumMap:                        make(map[values.Integer]int, 256),
		forgeFixedRecipeMap:              make(map[values.Integer]int, 256),
		forgeLevelMap:                    make(map[values.Integer]int, 256),
		forgeSupplementMap:               make(map[values.Integer]int, 256),
		gachaMap:                         make(map[values.Integer]int, 256),
		gachalistMap:                     make(map[values.Integer]map[values.Integer]int, 256),
		giftMap:                          make(map[values.Integer]int, 256),
		giftItemMap:                      make(map[values.Integer]map[values.Integer]int, 256),
		guideProcessMap:                  make(map[values.Integer]int, 256),
		guideStepMap:                     make(map[values.Integer]map[values.Integer]int, 256),
		guildMap:                         make(map[values.Integer]int, 256),
		guildJournalMap:                  make(map[values.Integer]int, 256),
		guildContendMap:                  make(map[values.Integer]int, 256),
		guildContendbuildMap:             make(map[values.Integer]int, 256),
		guildIntegralMap:                 make(map[values.Integer]int, 256),
		guildBlessingMap:                 make(map[values.Integer]int, 256),
		guildBossMap:                     make(map[values.Integer]int, 256),
		guildFunctionMap:                 make(map[values.Integer]int, 256),
		guildGvghelpMap:                  make(map[values.Integer]int, 256),
		guildPositionMap:                 make(map[values.Integer]int, 256),
		guildSignMap:                     make(map[values.Integer]int, 256),
		guildeMap:                        make(map[values.Integer]int, 256),
		headSculptureMap:                 make(map[values.Integer]int, 256),
		headSpeakMap:                     make(map[values.Integer]int, 256),
		headSpeakWordMap:                 make(map[values.Integer]map[values.Integer]int, 256),
		headTalkBubbleMap:                make(map[values.Integer]int, 256),
		heroMap:                          make(map[values.Integer]int, 256),
		heroDeviationEntryMap:            make(map[values.Integer]int, 256),
		homeAvatarMap:                    make(map[values.Integer]int, 256),
		imageDisplayLocationMap:          make(map[values.Integer]int, 256),
		imgLanguageMap:                   make(map[values.Integer]int, 256),
		inhibitAtkMap:                    make(map[values.Integer]int, 256),
		itemMap:                          make(map[values.Integer]int, 256),
		itemClassMap:                     make(map[values.Integer]int, 256),
		itemTypeIconMap:                  make(map[values.Integer]int, 256),
		journeyChestMap:                  make(map[values.Integer]int, 256),
		journeyListMap:                   make(map[values.Integer]int, 256),
		languageBackendMap:               make(map[values.Integer]int, 256),
		looptaskMap:                      make(map[values.Integer]int, 256),
		loopTaskStageRewardMap:           make(map[values.Integer]int, 256),
		mailMap:                          make(map[values.Integer]int, 256),
		mainCityMapMap:                   make(map[values.Integer]int, 256),
		mainCityMapBuildingMap:           make(map[values.Integer]int, 256),
		mainCityMapNpcPathMap:            make(map[values.Integer]int, 256),
		mainTaskMap:                      make(map[values.Integer]int, 256),
		mainTaskChapterMap:               make(map[values.Integer]int, 256),
		mainTaskChapterRewardMap:         make(map[values.Integer]map[values.Integer]int, 256),
		mainTaskChapterTargetMap:         make(map[values.Integer]int, 256),
		mapBuildingMap:                   make(map[values.Integer]int, 256),
		mapNpcMap:                        make(map[values.Integer]int, 256),
		mapNpcWithMainStoryMap:           make(map[values.Integer]map[values.Integer]int, 256),
		mapRelationMap:                   make(map[values.Integer]int, 256),
		mapSceneMap:                      make(map[values.Integer]int, 256),
		mapSelectMap:                     make(map[values.Integer]int, 256),
		mapTransmitMap:                   make(map[values.Integer]int, 256),
		mechanicsMap:                     make(map[values.Integer]int, 256),
		medicamentMap:                    make(map[values.Integer]int, 256),
		monsterMap:                       make(map[values.Integer]int, 256),
		monsterAttrMap:                   make(map[values.Integer]int, 256),
		monsterGroupMap:                  make(map[values.Integer]int, 256),
		noticeMap:                        make(map[values.Integer]int, 256),
		npcChallengeDungeonMap:           make(map[values.Integer]int, 256),
		npcDialogueMap:                   make(map[values.Integer]int, 256),
		dialogueWordMap:                  make(map[values.Integer]map[values.Integer]int, 256),
		dialogueOptMap:                   make(map[values.Integer]map[values.Integer]int, 256),
		npcTaskMap:                       make(map[values.Integer]int, 256),
		optionalBoxMap:                   make(map[values.Integer]int, 256),
		personalBossBuffMap:              make(map[values.Integer]int, 256),
		personalBossHelpPointsRewardMap:  make(map[values.Integer]int, 256),
		personalBossHelperCardsMap:       make(map[values.Integer]int, 256),
		personalBossLibraryMap:           make(map[values.Integer]int, 256),
		personalBossNumberFloorMap:       make(map[values.Integer]int, 256),
		personalBossLvMap:                make(map[values.Integer]map[values.Integer]int, 256),
		personalBossPassingRewardMap:     make(map[values.Integer]int, 256),
		planeDungeonMap:                  make(map[values.Integer]int, 256),
		popupMap:                         make(map[values.Integer]int, 256),
		qualityMap:                       make(map[values.Integer]int, 256),
		recycleTypeMap:                   make(map[values.Integer]int, 256),
		relicsMap:                        make(map[values.Integer]int, 256),
		relicsFunctionAttrMap:            make(map[values.Integer]int, 256),
		relicsLvMap:                      make(map[values.Integer]int, 256),
		relicsLvQualityMap:               make(map[values.Integer]map[values.Integer]int, 256),
		relicsSkillMap:                   make(map[values.Integer]int, 256),
		relicsSkilltypeMap:               make(map[values.Integer]int, 256),
		robotMap:                         make(map[values.Integer]int, 256),
		robotNameMap:                     make(map[values.Integer]int, 256),
		roguelikeArtifact1Map:            make(map[values.Integer]int, 256),
		roguelikeArtifact2Map:            make(map[values.Integer]int, 256),
		roguelikeArtifact3Map:            make(map[values.Integer]int, 256),
		roguelikeDungeonMap:              make(map[values.Integer]int, 256),
		roguelikeDungeonRoomMap:          make(map[values.Integer]map[values.Integer]int, 256),
		roguelikeEntryMap:                make(map[values.Integer]int, 256),
		roleChangemodelMap:               make(map[values.Integer]int, 256),
		roleLvMap:                        make(map[values.Integer]int, 256),
		roleLvTitleMap:                   make(map[values.Integer]int, 256),
		roleReachDungeonMap:              make(map[values.Integer]int, 256),
		roleReachItemMap:                 make(map[values.Integer]int, 256),
		roleSkillMap:                     make(map[values.Integer]int, 256),
		skillLvMap:                       make(map[values.Integer]map[values.Integer]int, 256),
		rowHeroMap:                       make(map[values.Integer]int, 256),
		sampleMap:                        make(map[values.Integer]int, 256),
		sampleChild1Map:                  make(map[values.Integer]map[values.Integer]int, 256),
		sampleChild2Map:                  make(map[values.Integer]map[values.Integer]int, 256),
		sensitiveDict1Map:                make(map[values.Integer]int, 256),
		sensitiveDict2Map:                make(map[values.Integer]int, 256),
		shieldedWordMap:                  make(map[values.Integer]int, 256),
		shopgoodslistMap:                 make(map[values.Integer]int, 256),
		goodslistLvMap:                   make(map[values.Integer]map[values.Integer]int, 256),
		sideSysEntryMap:                  make(map[values.Integer]int, 256),
		skillMap:                         make(map[values.Integer]int, 256),
		skillPosMap:                      make(map[values.Integer]int, 256),
		skillstoneMap:                    make(map[values.Integer]int, 256),
		soulContractMap:                  make(map[values.Integer]int, 256),
		specialResBarMap:                 make(map[values.Integer]int, 256),
		storyIllustrationMap:             make(map[values.Integer]int, 256),
		stringCnMap:                      make(map[values.Integer]int, 256),
		stringEnMap:                      make(map[values.Integer]map[values.Integer]int, 256),
		summonedMap:                      make(map[values.Integer]int, 256),
		systemMap:                        make(map[values.Integer]int, 256),
		systemUnlockConditionMap:         make(map[values.Integer]int, 256),
		talentMap:                        make(map[values.Integer]int, 256),
		talentAttrMap:                    make(map[values.Integer]int, 256),
		talentplateMap:                   make(map[values.Integer]int, 256),
		targetTaskMap:                    make(map[values.Integer]int, 256),
		targetTaskStageMap:               make(map[values.Integer]map[values.Integer]int, 256),
		taskTypeMap:                      make(map[values.Integer]int, 256),
		tempBagMap:                       make(map[values.Integer]int, 256),
		testBattleMap:                    make(map[values.Integer]int, 256),
		timelineMap:                      make(map[values.Integer]int, 256),
		towerDefaultMap:                  make(map[values.Integer]int, 256),
		verifyLanguageMap:                make(map[values.Integer]int, 256),
	}
}
