// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Actionfusion struct {
	Id            values.Integer            `mapstructure:"id" json:"id"`
	FusionTimeMap map[string]values.Integer `mapstructure:"fusion_time_map" json:"fusion_time_map"`
}

// parse func
func ParseActionfusion(data *Data) {
	if err := data.UnmarshalKey("actionfusion", &h.actionfusion); err != nil {
		panic(errors.New("parse table Actionfusion err:\n" + err.Error()))
	}
	for i, el := range h.actionfusion {
		h.actionfusionMap[el.Id] = i
	}
}

func (i *Actionfusion) Len() int {
	return len(h.actionfusion)
}

func (i *Actionfusion) List() []Actionfusion {
	return h.actionfusion
}

func (i *Actionfusion) GetActionfusionById(id values.Integer) (*Actionfusion, bool) {
	index, ok := h.actionfusionMap[id]
	if !ok {
		return nil, false
	}
	return &h.actionfusion[index], true
}
