// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type SideSysEntry struct {
	Id              values.Integer `mapstructure:"id" json:"id"`
	SideOrientation values.Integer `mapstructure:"side_orientation" json:"side_orientation"`
	BannerGroupId   values.Integer `mapstructure:"banner_group_id" json:"banner_group_id"`
}

// parse func
func ParseSideSysEntry(data *Data) {
	if err := data.UnmarshalKey("side_sys_entry", &h.sideSysEntry); err != nil {
		panic(errors.New("parse table SideSysEntry err:\n" + err.Error()))
	}
	for i, el := range h.sideSysEntry {
		h.sideSysEntryMap[el.Id] = i
	}
}

func (i *SideSysEntry) Len() int {
	return len(h.sideSysEntry)
}

func (i *SideSysEntry) List() []SideSysEntry {
	return h.sideSysEntry
}

func (i *SideSysEntry) GetSideSysEntryById(id values.Integer) (*SideSysEntry, bool) {
	index, ok := h.sideSysEntryMap[id]
	if !ok {
		return nil, false
	}
	return &h.sideSysEntry[index], true
}
