// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type GuildJournal struct {
	Id   values.Integer `mapstructure:"id" json:"id"`
	Text string         `mapstructure:"text" json:"text"`
}

// parse func
func ParseGuildJournal(data *Data) {
	if err := data.UnmarshalKey("guild_journal", &h.guildJournal); err != nil {
		panic(errors.New("parse table GuildJournal err:\n" + err.Error()))
	}
	for i, el := range h.guildJournal {
		h.guildJournalMap[el.Id] = i
	}
}

func (i *GuildJournal) Len() int {
	return len(h.guildJournal)
}

func (i *GuildJournal) List() []GuildJournal {
	return h.guildJournal
}

func (i *GuildJournal) GetGuildJournalById(id values.Integer) (*GuildJournal, bool) {
	index, ok := h.guildJournalMap[id]
	if !ok {
		return nil, false
	}
	return &h.guildJournal[index], true
}
