// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type MainCityMapBuilding struct {
	Id          values.Integer   `mapstructure:"id" json:"id"`
	BuildingPos []values.Integer `mapstructure:"building_pos" json:"building_pos"`
}

// parse func
func ParseMainCityMapBuilding(data *Data) {
	if err := data.UnmarshalKey("main_city_map_building", &h.mainCityMapBuilding); err != nil {
		panic(errors.New("parse table MainCityMapBuilding err:\n" + err.Error()))
	}
	for i, el := range h.mainCityMapBuilding {
		h.mainCityMapBuildingMap[el.Id] = i
	}
}

func (i *MainCityMapBuilding) Len() int {
	return len(h.mainCityMapBuilding)
}

func (i *MainCityMapBuilding) List() []MainCityMapBuilding {
	return h.mainCityMapBuilding
}

func (i *MainCityMapBuilding) GetMainCityMapBuildingById(id values.Integer) (*MainCityMapBuilding, bool) {
	index, ok := h.mainCityMapBuildingMap[id]
	if !ok {
		return nil, false
	}
	return &h.mainCityMapBuilding[index], true
}
