// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type StringCn struct {
	Id  values.Integer `mapstructure:"id" json:"id"`
	Txt string         `mapstructure:"txt" json:"txt"`
}

// parse func
func ParseStringCn(data *Data) {
	if err := data.UnmarshalKey("string_cn", &h.stringCn); err != nil {
		panic(errors.New("parse table StringCn err:\n" + err.Error()))
	}
	for i, el := range h.stringCn {
		h.stringCnMap[el.Id] = i
	}
}

func (i *StringCn) Len() int {
	return len(h.stringCn)
}

func (i *StringCn) List() []StringCn {
	return h.stringCn
}

func (i *StringCn) GetStringCnById(id values.Integer) (*StringCn, bool) {
	index, ok := h.stringCnMap[id]
	if !ok {
		return nil, false
	}
	return &h.stringCn[index], true
}
