// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type Enchantments struct {
	Id        values.Integer   `mapstructure:"id" json:"id"`
	Group     values.Integer   `mapstructure:"group" json:"group"`
	EquipSlot values.Integer   `mapstructure:"equip_slot" json:"equip_slot"`
	EquipJob  []values.Integer `mapstructure:"equip_job" json:"equip_job"`
}

// parse func
func ParseEnchantments(data *Data) {
	if err := data.UnmarshalKey("enchantments", &h.enchantments); err != nil {
		panic(errors.New("parse table Enchantments err:\n" + err.Error()))
	}
	for i, el := range h.enchantments {
		h.enchantmentsMap[el.Id] = i
	}
}

func (i *Enchantments) Len() int {
	return len(h.enchantments)
}

func (i *Enchantments) List() []Enchantments {
	return h.enchantments
}

func (i *Enchantments) GetEnchantmentsById(id values.Integer) (*Enchantments, bool) {
	index, ok := h.enchantmentsMap[id]
	if !ok {
		return nil, false
	}
	return &h.enchantments[index], true
}
