// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type EquipLight struct {
	Id          values.Integer   `mapstructure:"id" json:"id"`
	EffectsName []values.Integer `mapstructure:"effects_name" json:"effects_name"`
}

// parse func
func ParseEquipLight(data *Data) {
	if err := data.UnmarshalKey("equip_light", &h.equipLight); err != nil {
		panic(errors.New("parse table EquipLight err:\n" + err.Error()))
	}
	for i, el := range h.equipLight {
		h.equipLightMap[el.Id] = i
	}
}

func (i *EquipLight) Len() int {
	return len(h.equipLight)
}

func (i *EquipLight) List() []EquipLight {
	return h.equipLight
}

func (i *EquipLight) GetEquipLightById(id values.Integer) (*EquipLight, bool) {
	index, ok := h.equipLightMap[id]
	if !ok {
		return nil, false
	}
	return &h.equipLight[index], true
}
