// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type PersonalBossHelpPointsReward struct {
	Id                      values.Integer                    `mapstructure:"id" json:"id"`
	PlayerLevelRange        []values.Integer                  `mapstructure:"player_level_range" json:"player_level_range"`
	HelpPointsTreasureChest map[values.Integer]values.Integer `mapstructure:"help_points_treasure_chest" json:"help_points_treasure_chest"`
}

// parse func
func ParsePersonalBossHelpPointsReward(data *Data) {
	if err := data.UnmarshalKey("personal_boss_help_points_reward", &h.personalBossHelpPointsReward); err != nil {
		panic(errors.New("parse table PersonalBossHelpPointsReward err:\n" + err.Error()))
	}
	for i, el := range h.personalBossHelpPointsReward {
		h.personalBossHelpPointsRewardMap[el.Id] = i
	}
}

func (i *PersonalBossHelpPointsReward) Len() int {
	return len(h.personalBossHelpPointsReward)
}

func (i *PersonalBossHelpPointsReward) List() []PersonalBossHelpPointsReward {
	return h.personalBossHelpPointsReward
}

func (i *PersonalBossHelpPointsReward) GetPersonalBossHelpPointsRewardById(id values.Integer) (*PersonalBossHelpPointsReward, bool) {
	index, ok := h.personalBossHelpPointsRewardMap[id]
	if !ok {
		return nil, false
	}
	return &h.personalBossHelpPointsReward[index], true
}
