// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type RelicsSkilltype struct {
	Id   values.Integer `mapstructure:"id" json:"id"`
	Typ  string         `mapstructure:"typ" json:"typ"`
	Text string         `mapstructure:"text" json:"text"`
}

// parse func
func ParseRelicsSkilltype(data *Data) {
	if err := data.UnmarshalKey("relics_skilltype", &h.relicsSkilltype); err != nil {
		panic(errors.New("parse table RelicsSkilltype err:\n" + err.Error()))
	}
	for i, el := range h.relicsSkilltype {
		h.relicsSkilltypeMap[el.Id] = i
	}
}

func (i *RelicsSkilltype) Len() int {
	return len(h.relicsSkilltype)
}

func (i *RelicsSkilltype) List() []RelicsSkilltype {
	return h.relicsSkilltype
}

func (i *RelicsSkilltype) GetRelicsSkilltypeById(id values.Integer) (*RelicsSkilltype, bool) {
	index, ok := h.relicsSkilltypeMap[id]
	if !ok {
		return nil, false
	}
	return &h.relicsSkilltype[index], true
}
