// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type HeadTalkBubble struct {
	Id       values.Integer   `mapstructure:"id" json:"id"`
	Duration []values.Integer `mapstructure:"duration" json:"duration"`
	Content  string           `mapstructure:"content" json:"content"`
}

// parse func
func ParseHeadTalkBubble(data *Data) {
	if err := data.UnmarshalKey("head_talk_bubble", &h.headTalkBubble); err != nil {
		panic(errors.New("parse table HeadTalkBubble err:\n" + err.Error()))
	}
	for i, el := range h.headTalkBubble {
		h.headTalkBubbleMap[el.Id] = i
	}
}

func (i *HeadTalkBubble) Len() int {
	return len(h.headTalkBubble)
}

func (i *HeadTalkBubble) List() []HeadTalkBubble {
	return h.headTalkBubble
}

func (i *HeadTalkBubble) GetHeadTalkBubbleById(id values.Integer) (*HeadTalkBubble, bool) {
	index, ok := h.headTalkBubbleMap[id]
	if !ok {
		return nil, false
	}
	return &h.headTalkBubble[index], true
}
