// Code generated by exporter. DO NOT EDIT.
package rule_model

import (
	"errors"

	"coin-server/common/values"
)

// struct
type BuffLogic struct {
	Id       values.Integer `mapstructure:"id" json:"id"`
	LogicKey string         `mapstructure:"logic_key" json:"logic_key"`
	TextId   string         `mapstructure:"text_id" json:"text_id"`
}

// parse func
func ParseBuffLogic(data *Data) {
	if err := data.UnmarshalKey("buff_logic", &h.buffLogic); err != nil {
		panic(errors.New("parse table BuffLogic err:\n" + err.Error()))
	}
	for i, el := range h.buffLogic {
		h.buffLogicMap[el.Id] = i
	}
}

func (i *BuffLogic) Len() int {
	return len(h.buffLogic)
}

func (i *BuffLogic) List() []BuffLogic {
	return h.buffLogic
}

func (i *BuffLogic) GetBuffLogicById(id values.Integer) (*BuffLogic, bool) {
	index, ok := h.buffLogicMap[id]
	if !ok {
		return nil, false
	}
	return &h.buffLogic[index], true
}
